### ISSUE TITLE
Connect NodeJS backend to PostgreSQL database using `pg`.

### ISSUE THREAD

**Issue by andela-ioraelosi** [andela/kipit#26]
# Criteria
- 
# Optional
-  
# Tasks
- [x] Create a .gitignore for the project.
- [x] Create an .eslintrc file and configure. [eslint configuration](http://eslint.org/docs/user-guide/configuring.html), [description of eslint config](https://gist.github.com/cletusw/e01a85e399ab563b1236), [tutorial with eslint config](http://lxanders.github.io/posts/creating-a-base-for-developing-a-web-application-with-node/, https://kevinareed.com/2014/10/28/how-to-start-linting-javascript/)
- [x] Create package.json in repo.
- [x] Create a `src` folder. This folder will hold the source for the server and client code.
- [x] Install `express` for the simple server.
- [x] Create a simple server with `express`. Write the code in the `server.js` file in the `src` directory.
- [x] Install the `pg` module for the project.
- [x] Create a `config` folder in `src`.
- [x] Create a `config.js` file and `database.js` file in the `config` folder.
- [x] Add DB connection configuration (e.g database name, user e.t.c) to the `config.js` file.
- [x] Create a connection instance to the DB in `database.js`, using the connection config in `config.js`. Export the connection instance. [`pg.Client` documentation](https://github.com/brianc/node-postgres/wiki/Client), [Tutorial with `pg` connection](http://mherman.org/blog/2015/02/12/postgresql-and-nodejs/#.ViJyuRCrSYV)
- [x] Test the connection instance in the `server.js` file.
- [x] Define a ‘get’ method for the server in `server.js`.

**Comment by maryambabalola** [comment]
@andela-blawrence @andela-eakinyele @andela-rekemezie

**Comment by andela-ioraelosi** [comment]
Are @andela-eakinyele and @andela-rekemezie working on this issue? The assignee may need to be updated.

**Comment by emmyakin** [comment]
@andela-rekemezie

**Comment by emmyakin** [comment]
@andela-rekemezie

**Comment by emmyakin** [comment]
Are we required to query the database and write to the server when testing the connection instance 
Tasks 12 and 13? @andela-ioraelosi

**Comment by vitaly-t** [comment]
guys, check out [pg-promise](https://github.com/vitaly-t/pg-promise), if you want to save time when using PostgreSQL ;)
