### ISSUE TITLE
Set up testing for the server and database.

### ISSUE THREAD

**Issue by andela-ioraelosi** [andela/kipit#36]
# Learning outcomes
- How to write a simple unit test using `jasmine-node`.
- How to write a simple functional test using `jasmine-node` and `supertest`.
# Tasks
- [x] Create a ‘spec’ folder in the application root.
- [x] Create the ‘unit’, ‘functional’ and ‘fixtures’ directories in the ‘spec’ directory.
- [x] Create a ‘core’ directory in the ‘functional’ directory.
- [x] Create a core.server.spec.js file in ‘core’.
- [x] Create a test to verify the server returns the appropriate response. Run the tests.
- [x] Create a ‘database.spec.js’ file in a ‘database’ directory in the ‘unit’ folder of the ‘spec’ folder.
- [x] Create a test to verify the app is connected to the correct database. Run the tests.

**Comment by bolutife-lawrence** [comment]
@andela-mbabalola

**Comment by bolutife-lawrence** [comment]
@andela-ioraelosi I downloaded jasmine and added it as a dependency to the project, but it currently resides in the node_modules directory, I'm i to pull it out to the root directory or leave it there and then reference it from there? Thanks. (

**Comment by bolutife-lawrence** [comment]
I'm trying to use the node module 'supertest', but I keep running into the issue of overwriting the already existing instance of 'app' created from express. Without supertest, the test would pass or fail as expected.
