### ISSUE TITLE
Refactor application server to follow best practices. 

### ISSUE THREAD

**Issue by andela-ioraelosi** [andela/kipit#44]
# Tasks
- [x] Create the `environment` directory in the `config` directory. 
- [x] Create the configurations (database, environment variable e.t.c) for the `development`, `test`, `staging` and `production` servers in the `environment` directory using a file for each configuration e.g `test.js` for the `test` config.

``` javascript
// Sample configuration
{
  'test': {
    db: {
      user: '',
      password: '',
      database: '',
      host: '',
      port: ''
    }
  }
}
```
- [x] Refactor the code in `database.js` to use the configuration. **Note that the connection configuration for the `staging` and `production` servers is not in an object but in a connection URI.**
- [x] Refactor the `test` command to change the `NODE_ENV` to `test` before running any tests.
- [x] Create an `express.js` file in the `config` directory and move the configuration for the server to that file. Export the application from the file.
- [x] Refactor `server.js` to use the configuration.
- [x] Refactor the server test (`core.server.spec.js`) to use the configuration.

**Comment by rowlandekemezie** [comment]
@andela-eakinyele

**Comment by rowlandekemezie** [comment]
task #2: which file should contain the configurations; _config.js_ or _environment.js?_
task #5: which configuration is to be moved? Do you mean we should _require_ it.

We need a bit of clarity on the above and any other helpful guide.

**Comment by andela-ioraelosi** [comment]
Task `2`: There was an error in the task specification. I've modified tasks `1` and `2`.
Task `5`: The `server.js` file should contain only code for server initialization. Configuration such as middleware usage, route definitions and database connections should reside in the `express.js` file. The app will be configured in the `express.js` file and required in the `server.js` file.
